<MyLayout>
    BoxLayout:
        orientation: "vertical"
        #orientation: "horizontal"
        size: root.width, root.height

        padding: 20
        spacing: 20

        Button:
            text: "Hello world!"
           

        Button:
            text: "Good Bye! world!"

        Button:
            text: "I'm Hungry!"
            pos_hint: {"center_x":0.5}
            size_hint: (1, .1)

            width: 200
            height: 50