<MyLayout>
    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height

        Carousel:
            direction: "bottom"

            Image:
                source: "images/morning600.jpg"

            Image:
                source: "images/alienware600.jpg"

            Image:
                source: "images/alienware2600.jpg"

            Image:
                source: "images/razer600.jpg"
