MDBoxLayout:   
    orientation: "vertical"
    

    MDScreen:

        MDLabel:
            id: my_label
            text: "Some Stuff"
            halign: "center"

        MDFloatingActionButtonSpeedDial:
            data: app.data
            root_button_anim: True

            label_text_color: 0,0.7,0.7,1
            bg_color_stack_button: 0.3, 0.3, 0.3, 1
            bg_color_root_button: 0.3, 0.3, 0.3, 1
            color_icon_root_button:  0,0.7,0.7,1
            color_icon_stack_button: 0,0.7,0.7,1

            callback: app.callback
            on_open: app.open()
            on_close: app.close()
            

