AnchorLayoutExample:
<AnchorLayoutExample>:
    # right, left, center
    anchor_x: "right"
    # bottom, top, center 
    # anchor_y: 
    #Button:
    #        text: "Hello"
    #        size_hint: .2, .2

    BoxLayout:
        size_hint: .2, .2
        
        Button:
            text: "Hello"
            #size_hint: .2, .2

        Button:
            text: "Hello"
            #size_hint: .2, .2

    