; Hello World assembly program
; 
; Author: Suraj Gupta
; Date: 9-07-2021

DATA SEGMENT
    MSG DB "HELLO WORLD$"
DATA ENDS

CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:    MOV AX,DATA
    MOV DS,AX
    MOV AH,09H
    MOV DX,OFFSET MSG
    INT 21H
    MOV AH,4CH
    INT 21H
CODE ENDS
END START